### ISSUE TITLE
[Bug]del删除操作，看了源码发现参数不对

### ISSUE THREAD

**Issue by wython** [LiShiSangZi/egg-memcached#1]
![image](https://user-images.githubusercontent.com/15258919/44657755-97660d80-aa30-11e8-920d-0c078329b6cc.png)

**Comment by wv1124** [comment]
https://github.com/LiShiSangZi/egg-memcached/pull/2

**Comment by LiShiSangZi** [comment]
Merged and published. Thanks for the contribution.
